esphome:
  name: peti-fan
  restore_from_flash: true
  early_pin_init: false

esp8266:
  board: d1_mini_lite

preferences:
  flash_write_interval: 5min

# Enable logging
logger:
  baud_rate: 0 # disable UART

# Enable Home Assistant API
api:
  #password: !secret api.password
  encryption:
    key: !secret api.key

ota:
  - platform: esphome
    password: !secret ota.password

wifi:
  ssid: !secret wifi.ssid
  password: !secret wifi.password
  domain: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Robi-Fan Fallback Hotspot"
    password: !secret wifi.ap.password

captive_portal:

sensor:
  - platform: pulse_counter
    pin:
      number: D2
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Robi Fan RPM"
    id: robi_fan_rpm
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 15s

output:
  - platform: esp8266_pwm
    id: robi_fan_pwm
    pin: D1
    frequency: "10000 Hz"

    # min_power: 0%
    # max_power: 100%

fan:
  - platform: speed
    output: robi_fan_pwm
    name: "Robi fan"
    id: robi_fan
