# lots of dirty pins on esp32-c3!
# GPIO0+1 are used for rx/tx; pulse_counter counted phantom signals and PWM had noise
# GPIO2+3;20+21 seem to be clean.

esphome:
  name: robi-fan
  restore_from_flash: true
  early_pin_init: false

  ### no need -- default value is 0
  # on_boot:
  #   priority: 1000
  #   then:
  #     - delay: 1s
  #     - fan.turn_on: robi_fan
  #     - output.turn_on: robi_fan_pwm
  #     - output.set_level:
  #         id: robi_fan_pwm
  #         level: 0%

preferences:
  flash_write_interval: 5min

# mdns:
#   disabled: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  baud_rate: 0 # disable UART

# Enable Home Assistant API
api:
  #password: !secret api.password
  encryption:
    key: !secret api.key

ota:
  - platform: esphome
    password: !secret ota.password

wifi:
  power_save_mode: none
  # a fritzbox AP mellett van. az ott a LAN-ra route-ol, szoval elerheto.
  ssid: !secret wifi.home.ssid
  password: !secret wifi.home.password
  domain: ""
  #use_address:
  
  # static_ip seems to get disabled after first reboot
  # manual_ip:
  #   static_ip: !secret ip.robi-fan
  #   gateway: !secret ip.gateway
  #   subnet: !secret ip.subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Robi-Fan Fallback Hotspot"
    password: !secret wifi.ap.password

captive_portal:


sensor:
  - platform: pulse_counter
    pin:
      number: GPIO5
      # inverted: true
    name: "Robi Fan RPM"
    id: robi_fan_rpm
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5
    update_interval: 10s

  - platform: internal_temperature
    name: "ESP Temperature"

  - platform: wifi_signal
    name: Signal strength

  - platform: uptime
    name: Uptime

output:
  - platform: ledc
    id: robi_fan_pwm
    pin:
      number: GPIO7
    frequency: "40000 Hz"
    min_power: 0%
    max_power: 60%

fan:
  - platform: speed
    output: robi_fan_pwm
    name: "Robi fan"
    id: robi_fan
    restore_mode: RESTORE_DEFAULT_OFF
